---
# tasks file for node_exporter
  - name: Create archives and node_exporter directories
    file:
      name: "{{ item }}"
      state: directory
    with_items:
      - "{{ archives_dir }}"
      - "{{ node_exporter_dir }}"
  - name: Download node_exporter archive
    get_url:
      url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
      dest: "{{ archives_dir }}"
  - include_tasks: "{{ ansible_facts.service_mgr }}.yml"
